# Generated by Django 3.1.7 on 2021-04-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('stay_id', models.TextField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('receipts', models.JSONField()),
            ],
        ),
    ]
