# Generated by Django 3.1.7 on 2021-05-05 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stay_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datein', models.DateField()),
                ('dateout', models.DateField()),
                ('data', models.BooleanField()),
                ('receipt', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Stay',
        ),
        migrations.AddField(
            model_name='stay_data',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
        migrations.AddConstraint(
            model_name='stay_data',
            constraint=models.UniqueConstraint(fields=('email', 'datein', 'dateout'), name='unique_stay'),
        ),
    ]
