version: '3'
services:
    postgres:
        restart: always
        image: lmmdock/postgres-multi:latest
        volumes:
            - postgres-storage:/var/lib/postgres
        environment:
            - POSTGRES_DATABASES=dataretentiondb:${DATA_USER}
            - POSTGRES_USERS=${DATA_USER}:${DATA_PASSWORD}
        ports:
            - "5432:5432"
        restart: always
    
    dataRetention:
        build: ./dataRetention
        volumes:
            - ./dataRetention:/app
        ports:
            - "8000:80"
        depends_on:
            - postgres
        command: bash -c "sleep 5 && python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:80"
        restart: always
    

volumes:
    postgres-storage:
      driver: local
      driver_opts:
        o: bind
        type: none
        device: ./postgres
    