version: '3'
services:
    postgres:
        restart: always
        image: lmmdock/postgres-multi:latest
        volumes:
            - postgres-storage:/var/lib/postgres
        environment:
            - POSTGRES_DATABASES=dataretentiondb:${DATA_USER}
            - POSTGRES_USERS=${DATA_USER}:${DATA_PASSWORD}
        ports:
            - "5432:5432"
        restart: always
    

volumes:
    postgres-storage:
      driver: local
      driver_opts:
        o: bind
        type: none
        device: ./postgres
    